# Default configuration for Unbound Manager
server_ip: "127.0.0.1"
num_threads: 4
msg_cache_size: "64m"
rrset_cache_size: "128m"
cache_min_ttl: 300
cache_max_ttl: 86400
verbosity: 1
do_ip4: true
do_ip6: false
do_udp: true
do_tcp: true
prefer_ip6: false